---
- hosts: test
  gather_facts: no
  become: true
  tasks:

  - name: Add group
    group:
      name: superusers
      state: present

  - name: Add user2
    user:
      name: user2
      groups: superusers

  - name: Add user3
    user:
      name: user3
      groups: superusers

  - name: Validate the sudoers file before saving
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      insertbefore: '#includedir /etc/sudoers.d'
      line: '%superusers ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s

#  - name: creating .ssh directory
#    file:
#      path: /home/user1/.ssh
#      owner: user1
#      group: user1
#      state: directory

#  - name: copy key
#    copy:
#      src: /home/user1/.ssh/id_rsa.pub
#      dest: /home/user1/.ssh/id_rsa.pub
#      owner: user1
#      group: user1

#  -  name: Установить authorized key из файла id_rsa.pub
#     authorized_key:
#       user: user1
#       state: present
#       key: "{{ lookup('file', '/home/user1/.ssh/id_rsa.pub') }}"
#       path: /home/user1/.ssh/authorized_keys
#       manage_dir: False

